
#include <hcYmzShield.h>

void setup() {
  Serial.begin(9600);
  Serial.println("MIDI2PSG Output");
}


void loop() {
  YMZ.setVolume(0xa);
  // 
  YMZ.setTempo(138);
  YMZ.beat( 1);
  YMZ.setChannels(SKIP, SKIP,   70,   39,   51, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   70,   46, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   70,   51, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   70,   49, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   44,   49, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   70,   47,   47, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   66,   42, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   63,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   47, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   47,  OFF, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP,   49, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   49, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70,   39,   51, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   70,   46, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   70,   51, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   70,   49, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   44,   49, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   70,   47,   47, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   66,   42, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   63,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   47, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   47,  OFF, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP,   49, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   49, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32,   44, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   32, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   70,   32, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   63,   32, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   44, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,  OFF,   34,   46, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   61, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   34, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   66,   34, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   68,   34, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   35,   47, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   58, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   35, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   66,   35, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   70,   35, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   37,   49, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   73, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   73,   44,   46, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   46, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68,   41,   49, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   73,   42,   51, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   68,   44,   49, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  65, SKIP,  OFF,   39,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   51, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   49, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  58, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  61, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  65, SKIP,  OFF,   34, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   65,   34, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,  OFF,  OFF, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  65, SKIP, SKIP,   34, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   65,   34, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   65,   41, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  61, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   65,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63, SKIP,  OFF,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   32, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63, SKIP,   68,   32, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  65, SKIP,   68,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,   68,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  61, SKIP,  OFF,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  70, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,  OFF,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  68, SKIP, SKIP,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,   66,   37, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  65, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  66, SKIP,   66,   41, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  65, SKIP,  OFF,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   51, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   49, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  65, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   66,   42, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  58, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  61, SKIP,  OFF,   34, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   65,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  65, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   65,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  70, SKIP, SKIP,   34, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  70, SKIP,   65,   34, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  71, SKIP,   65,   41, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  70, SKIP,   65,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,  OFF,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   32, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  66, SKIP, SKIP,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   32, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   68,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  65, SKIP, SKIP,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  65, SKIP,  OFF,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,  OFF,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  65, SKIP, SKIP,   37, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   66,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  65, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   41, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   65,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   44, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   58, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   46, SKIP,   58); YMZ.beat(16);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP,   61); YMZ.beat(16);
  YMZ.setChannels(SKIP,   63,   66,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   66,  OFF,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   44, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   46, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP,   61); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   44, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   63,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   63,   68,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65,   68,   46, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   66,   68,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(SKIP,   61,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   61); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   68, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,  OFF,   42, SKIP,   68); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   66,   66,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65,   66,   46, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   66,   66,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   66, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(SKIP,   63,   66,   44, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   46, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   58,   66,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   58); YMZ.beat(16);
  YMZ.setChannels(SKIP,   61,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   61); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,  OFF,   42, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   70); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70,   65,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   70); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   71,   65,   46, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   71); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73,   65,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   73); YMZ.beat(16);
  YMZ.setChannels(  70,   73,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   73); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  70,   73,  OFF,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP, SKIP,   73); YMZ.beat(16);
  YMZ.setChannels(  68,   71, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   71); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68,   44, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   71, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68,   46, SKIP,   71); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  61,   70,   68,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   70); YMZ.beat(16);
  YMZ.setChannels(  61,   65,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63,   66,  OFF,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(  65,   68, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   68); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   44, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  61,   65, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   46, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(  63,   66, SKIP, SKIP, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(SKIP,   68,   66,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   68); YMZ.beat(16);
  YMZ.setChannels(  65,   68,  OFF,   32, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   68); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   44, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63,   66,  OFF,   32, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(  61,   65,   68,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  63,   66, SKIP,   46, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(  65,   68, SKIP,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   68); YMZ.beat(16);
  YMZ.setChannels(  61,   65,   70,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  63,   63, SKIP,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   70,   35, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   35, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70,   35, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63,   63, SKIP,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(  61,   65,  OFF,   35, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(  63,   66, SKIP,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(  63,   65,  OFF,   35, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   66, SKIP, SKIP, SKIP,   65); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(32);
  YMZ.setChannels(  65,   68,   70,   47, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   68); YMZ.beat(16);
  YMZ.setChannels(  66,   70,  OFF,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP,   70); YMZ.beat(16);
  YMZ.setChannels(  73,   68,   73,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   68); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  70,   66, SKIP,   49, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(  73,   65, SKIP,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(  73,   61,   73,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   61); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  75,   63,   75,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(  75,   63,   75,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39,   51, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70,   51, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   41,   56, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   73,   53, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   41, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   42,   54, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   73,   54,   54, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   42,   54, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32,   56, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   75,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32,   53, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32,   53, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   37,   49, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP, SKIP,   37,   49, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   37,   49, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   49, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   49, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   73,   37,   49, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   37,   49, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   37,   49, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   49, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   37,   49, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70,   35,   47, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   35, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   35, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   37,   49, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP, SKIP,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70,   39,   51, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   70,   46, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   70,   51, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   70,   49, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   44,   49, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   70,   47,   47, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   66,   42, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   63,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   47, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   47,  OFF, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP,   49, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   49, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70,   39,   51, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   70,   46, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   70,   51, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   70,   49, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   44,   49, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   70,   47,   47, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   66,   42, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   63,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   47, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   47,  OFF, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP,   49, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   49, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32,   44, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   32, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   70,   32, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   63,   32, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   44, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,  OFF,   34,   46, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   61, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   34, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   66,   34, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   68,   34, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   35,   47, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   58, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   35, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   66,   35, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   70,   35, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   37,   49, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   73, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   73,   44,   46, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   46, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68,   41,   49, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   73,   42,   51, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   68,   44,   49, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  65, SKIP,  OFF,   39,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   51, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   49, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  58, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  61, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  65, SKIP,  OFF,   34, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   65,   34, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,  OFF,  OFF, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  65, SKIP, SKIP,   34, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   65,   34, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   65,   41, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  61, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   65,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63, SKIP,  OFF,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   32, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63, SKIP,   68,   32, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  65, SKIP,   68,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,   68,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  61, SKIP,  OFF,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  70, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,  OFF,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  68, SKIP, SKIP,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,   66,   37, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  65, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  66, SKIP,   66,   41, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  65, SKIP,  OFF,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   51, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   49, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  65, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   66,   42, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  58, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  61, SKIP,  OFF,   34, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   65,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  65, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   65,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  70, SKIP, SKIP,   34, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  70, SKIP,   65,   34, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  71, SKIP,   65,   41, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  70, SKIP,   65,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,  OFF,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   32, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  66, SKIP, SKIP,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   32, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   68,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  65, SKIP, SKIP,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   68,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  65, SKIP,  OFF,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,  OFF,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  65, SKIP, SKIP,   37, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP,   66,   37, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  65, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   41, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   65,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   66,   44, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   58, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   46, SKIP,   58); YMZ.beat(16);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP,   61); YMZ.beat(16);
  YMZ.setChannels(SKIP,   63,   66,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   66,  OFF,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   44, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   46, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP,   61); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   44, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   63,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   63,   68,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65,   68,   46, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   66,   68,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(SKIP,   61,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   61); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   68, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,  OFF,   42, SKIP,   68); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   66,   66,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65,   66,   46, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   66,   66,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   66, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(SKIP,   63,   66,   44, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   46, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   58,   66,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   58); YMZ.beat(16);
  YMZ.setChannels(SKIP,   61,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   61); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,  OFF,   42, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   70); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70,   65,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   70); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   71,   65,   46, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   71); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73,   65,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   73); YMZ.beat(16);
  YMZ.setChannels(  70,   73,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   73); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  70,   73,  OFF,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP, SKIP,   73); YMZ.beat(16);
  YMZ.setChannels(  68,   71, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   71); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68,   44, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   71, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   68,   46, SKIP,   71); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  61,   70,   68,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   70); YMZ.beat(16);
  YMZ.setChannels(  61,   65,  OFF,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63,   66,  OFF,   42, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(  65,   68, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   68); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   44, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  61,   65, SKIP,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   46, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(  63,   66, SKIP, SKIP, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(SKIP,   68,   66,   44, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   68); YMZ.beat(16);
  YMZ.setChannels(  65,   68,  OFF,   32, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   68); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66,   44, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63,   66,  OFF,   32, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(  61,   65,   68,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  63,   66, SKIP,   46, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(  65,   68, SKIP,   34, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   68); YMZ.beat(16);
  YMZ.setChannels(  61,   65,   70,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  63,   63, SKIP,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   70,   35, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   35, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70,   35, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63,   63, SKIP,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(  61,   65,  OFF,   35, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(  63,   66, SKIP,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(  63,   65,  OFF,   35, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   66, SKIP, SKIP, SKIP,   65); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(32);
  YMZ.setChannels(  65,   68,   70,   47, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   68); YMZ.beat(16);
  YMZ.setChannels(  66,   70,  OFF,   35, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   70, SKIP, SKIP,   70); YMZ.beat(16);
  YMZ.setChannels(  73,   68,   73,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   68); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  70,   66, SKIP,   49, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   66); YMZ.beat(16);
  YMZ.setChannels(  73,   65, SKIP,   37, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   65); YMZ.beat(16);
  YMZ.setChannels(  73,   61,   73,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   61); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  75,   63,   75,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(  75,   63,   75,   39, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   63); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   39,   51, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   70,   51, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   39, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   41,   56, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   73,   53, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   41, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   42,   54, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   73,   54,   54, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,  OFF,   42,   54, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32,   56, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   75,   32, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32,   53, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   32,   53, SKIP); YMZ.beat( 4);
  YMZ.setChannels( OFF,  OFF,  OFF,  OFF,  OFF,  OFF); YMZ.mute();
   delay(3000); // Repeat every 3 seconds
}
