
#include <hcYmzShield.h>

void setup() {
  Serial.begin(9600);
  Serial.println("MIDI2PSG Output");
}


void loop() {
  YMZ.setVolume(0xa);
  // 
  YMZ.setTempo(112);
  delay(4286);
  YMZ.setChannels(SKIP,   48,   84, SKIP, SKIP,   72); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   48, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP,   48, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP,   48, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 2);
  YMZ.setChannels(SKIP,   44,   84, SKIP, SKIP,   72); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   44, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP,   44, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP,   44, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 2);
  YMZ.setChannels(SKIP,   46,   82, SKIP, SKIP,   70); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   46, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP,   46, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP,   46, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 2);
  YMZ.setChannels(SKIP,   43,   83, SKIP, SKIP,   71); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   43, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP,   43, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(SKIP,   43,   86, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   83, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   79, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   77, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   74, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   67, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   65, SKIP, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(  72,   48,   72,   60,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   48, SKIP,   63, SKIP,   75); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF, SKIP,   67, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   48, SKIP, SKIP, SKIP,   75); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   72, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   48, SKIP,   60, SKIP,   75); YMZ.beat( 8);
  YMZ.setChannels(  72, SKIP,   72,   63,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   75,   67,   75, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74, SKIP,   74,   72,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  72,   46,   72,   58,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   55, SKIP,   60, SKIP,   75); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   46, SKIP,   63, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   51, SKIP, SKIP, SKIP,   75); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   67, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   46, SKIP,   58, SKIP,   75); YMZ.beat( 8);
  YMZ.setChannels(  72, SKIP,   72,   60,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP,   79,   63,   79, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   75,   67,   75, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  72,   44,   72,   56,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   44, SKIP,   60, SKIP,   75); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF, SKIP,   63, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   44, SKIP, SKIP, SKIP,   75); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   67, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   44, SKIP,   56, SKIP,   75); YMZ.beat( 8);
  YMZ.setChannels(  72, SKIP,   72,   60,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  77, SKIP,   77,   63,   77, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   75,   67,   75, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74,   46,   74,   58,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   53, SKIP,   62, SKIP,   74); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   46, SKIP,   65, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   50, SKIP, SKIP, SKIP,   74); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   70, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   46, SKIP,   58, SKIP,   74); YMZ.beat( 8);
  YMZ.setChannels(  74, SKIP,   74,   62,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   75,   65,   75, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  77, SKIP,   77,   70,   77, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79,   51,   79,   63,   79, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   51, SKIP,   67, SKIP,   79); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF, SKIP,   70, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   51, SKIP, SKIP, SKIP,   79); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   75, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   51, SKIP,   63, SKIP,   79); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP,   79,   67,   79, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  84, SKIP,   84,   70,   84, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  82, SKIP,   82,   75,   82, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80,   53,   80,   65,   80, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   60, SKIP,   70, SKIP,   80); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   53, SKIP,   72, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   56, SKIP, SKIP, SKIP,   80); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   77, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   53, SKIP,   65, SKIP,   80); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   80,   70,   80, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  77, SKIP,   77,   72,   77, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74, SKIP,   74,   77,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71,   55,   71,   67,   71, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   55, SKIP,   71, SKIP,   77); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF, SKIP,   74, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   55, SKIP, SKIP, SKIP,   77); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   77, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74,   55,   74,   67,   74,   77); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   71, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   74, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   77, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79,   55,   79,   67,   79, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   62, SKIP,   71, SKIP,   83); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   55, SKIP,   74, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   59, SKIP, SKIP, SKIP,   83); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   77, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   55, SKIP,   74, SKIP,   83); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   71, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   67, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   65, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  72,   48,   72,   60,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   48, SKIP,   63, SKIP,   75); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF, SKIP,   67, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   48, SKIP, SKIP, SKIP,   75); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   72, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   48, SKIP,   60, SKIP,   75); YMZ.beat( 8);
  YMZ.setChannels(  72, SKIP,   72,   63,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   75,   67,   75, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74, SKIP,   74,   72,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  72,   46,   72,   58,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   55, SKIP,   60, SKIP,   75); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   46, SKIP,   63, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   51, SKIP, SKIP, SKIP,   75); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   67, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   46, SKIP,   58, SKIP,   75); YMZ.beat( 8);
  YMZ.setChannels(  72, SKIP,   72,   60,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP,   79,   63,   79, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   75,   67,   75, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  72,   44,   72,   56,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   44, SKIP,   60, SKIP,   75); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF, SKIP,   63, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   44, SKIP, SKIP, SKIP,   75); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   67, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   44, SKIP,   56, SKIP,   75); YMZ.beat( 8);
  YMZ.setChannels(  72, SKIP,   72,   60,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  77, SKIP,   77,   63,   77, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   75,   67,   75, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74,   46,   74,   58,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   53, SKIP,   62, SKIP,   74); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   46, SKIP,   65, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   50, SKIP, SKIP, SKIP,   74); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   70, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   46, SKIP,   58, SKIP,   74); YMZ.beat( 8);
  YMZ.setChannels(  74, SKIP,   74,   62,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   75,   65,   75, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  77, SKIP,   77,   70,   77, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79,   51,   79,   63,   79, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   51, SKIP,   67, SKIP,   79); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF, SKIP,   70, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   51, SKIP, SKIP, SKIP,   79); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   75, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   51, SKIP,   63, SKIP,   79); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP,   79,   67,   79, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  84, SKIP,   84,   70,   84, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  82, SKIP,   82,   75,   82, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80,   53,   80,   65,   80, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   60, SKIP,   70, SKIP,   80); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   53, SKIP,   72, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   56, SKIP, SKIP, SKIP,   80); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   77, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   53, SKIP,   65, SKIP,   80); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   80,   70,   80, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  77, SKIP,   77,   72,   77, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74, SKIP,   74,   77,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71,   55,   71,   67,   71, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   55, SKIP,   71, SKIP,   77); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF, SKIP,   74, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   55, SKIP, SKIP, SKIP,   77); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   77, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74,   55,   74,   67,   74,   77); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   71, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   74, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   77, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79,   55,   79,   67,   79, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   62, SKIP,   71, SKIP,   83); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   55, SKIP,   74, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   59, SKIP, SKIP, SKIP,   83); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   77, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   55, SKIP,   74, SKIP,   83); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   71, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   67, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   65, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF,  OFF,  OFF,  OFF,  OFF,  OFF); YMZ.mute();
   delay(3000); // Repeat every 3 seconds
}
