
#include <hcYmzShield.h>

void setup() {
  Serial.begin(9600);
  Serial.println("MIDI2PSG Output");
}


void loop() {
  YMZ.setVolume(0xa);
  // 
  YMZ.setTempo(124);
   YMZ.setChannels(OFF,   74, OFF, OFF, OFF, OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   81, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   81, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   81, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  38,   74, SKIP, SKIP,   62, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  50,   77, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   79, SKIP, SKIP,   64, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP,   65, SKIP); YMZ.beat(16);
  YMZ.setChannels(  55,   70, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  43,   79, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(  36,   76, SKIP, SKIP,   72, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  48,   79, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(  53,   69, SKIP, SKIP,   65, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  41,   77, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP,   65, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  34,   74, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  46,   77, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP,   72, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(  55,   74, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  43,   77, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(  33,   76, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  45,   76, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  45,   81, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  45,   73, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  45,   81, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(  43,   73, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(  41,   81, SKIP, SKIP,   65, SKIP); YMZ.beat(16);
  YMZ.setChannels(  40,   73, SKIP, SKIP,   64, SKIP); YMZ.beat(16);
  YMZ.setChannels(  38,   77, SKIP, SKIP,   62, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  50,   77, SKIP, SKIP,   62, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP,   62, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   79, SKIP, SKIP,   64, SKIP); YMZ.beat(16);
  YMZ.setChannels(  55,   81, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   82, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  43,   79, SKIP, SKIP,   67, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(  36,   79, SKIP, SKIP,   72, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  48,   79, SKIP, SKIP,   72, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   79, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(  53,   79, SKIP, SKIP,   65, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   81, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  41,   77, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP,   65, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  34,   77, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  46,   74, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP,   72, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(  55,   77, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  43,   74, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(  33,   76, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  45,   76, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  45,   81, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  45,   73, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  45,   81, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(  43,   73, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(  41,   81, SKIP, SKIP,   65, SKIP); YMZ.beat(16);
  YMZ.setChannels(  40,   73, SKIP, SKIP,   64, SKIP); YMZ.beat(16);
  YMZ.setChannels(  38,   77, SKIP, SKIP,   62, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  50,   77, SKIP, SKIP,   62, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP,   64, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   79, SKIP, SKIP,   65, SKIP); YMZ.beat(16);
  YMZ.setChannels(  55,   81, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   82, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  43,   79, SKIP, SKIP,   67, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(  36,   79, SKIP, SKIP,   72, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  48,   79, SKIP, SKIP,   72, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   72, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   79, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(  53,   79, SKIP, SKIP,   65, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   65, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   81, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  41,   77, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP,   65, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  34,   77, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   70, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  46,   74, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP,   72, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(  55,   77, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  43,   74, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP,   70, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(  33,   76, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  45,   76, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   73, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  45,   81, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  45,   73, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  45,   81, SKIP, SKIP,   69, SKIP); YMZ.beat(16);
  YMZ.setChannels(  43,   73, SKIP, SKIP,   67, SKIP); YMZ.beat(16);
  YMZ.setChannels(  41,   81, SKIP, SKIP,   65, SKIP); YMZ.beat(16);
  YMZ.setChannels(  40,   73, SKIP, SKIP,   64, SKIP); YMZ.beat(16);
  YMZ.setChannels(  38,   74, SKIP, SKIP,   62, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setVolume(0x9);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setVolume(0x8);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  38,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setVolume(0x7);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setVolume(0x6);
  YMZ.setChannels(  38,   74, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setVolume(0x5); YMZ.beat(8);
  YMZ.setChannels( OFF,  OFF,  OFF,  OFF,  OFF,  OFF); YMZ.mute();
   delay(3000); // Repeat every 3 seconds
}
