/**
 * Hardchord MIDI Converter (hcmidi.php)
 * Derrick Sobodash <derrick@sobodash.com>
 * Version 0.1.0
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer. 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution. 
 */

#include <hcYmzShield.h>

void setup() {
  Serial.begin(9600);
  Serial.println("Generated by Hardchord MIDI2PSG Converter!");
}


void loop() {
  // M1item
  YMZ.setVolume(8);
  YMZ.setTempo(120);
   YMZ.setChannels(  72,   46,  OFF,   53,  OFF,  OFF); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   58, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  69, SKIP, SKIP,   60, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  67,   45, SKIP,   64, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  64, SKIP, SKIP,   60, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  60, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  64, SKIP, SKIP,   60, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74,   39, SKIP,   65, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  70, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  67, SKIP, SKIP,   58, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  63, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF,   38,   64,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP,  OFF,   64,  OFF, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(64, TRIPLEDOT);
  YMZ.setChannels( OFF,  OFF,  OFF,  OFF,  OFF,  OFF); YMZ.mute();
  delay(3000); // Repeat every 3 seconds
}
