/**
 * Deck BGM from Pirate Ship Higemaru
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer. 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution. 
 */

#include <hcYmzShield.h>


void setup() {
  Serial.begin(9600);
  Serial.println("Deck BGM - Pirate Ship Higemaru by Ayako Mori, Tamayo Kawamoto"); 
}

void loop() {
  delay(22);
  YMZ.setTonePeriod(3, 0);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 0);
  YMZ.setTone(3, true);
  YMZ.setTone(4, true);
  YMZ.setTone(5, true);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTonePeriod(1, 0);
  YMZ.setTonePeriod(2, 0);
  YMZ.setNoisePeriod(8);
  YMZ.setVolume(0, 14);
  YMZ.setVolume(1, 7);
  YMZ.setVolume(2, 7);
  delay(5);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setTonePeriod(3, 360);
  YMZ.setTonePeriod(4, 427);
  YMZ.setTonePeriod(5, 480);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 8);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(53);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setVolume(3, 4);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(53);
  YMZ.setTonePeriod(3, 381);
  YMZ.setTonePeriod(4, 453);
  YMZ.setTonePeriod(5, 507);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setTonePeriod(3, 360);
  YMZ.setTonePeriod(4, 427);
  YMZ.setTonePeriod(5, 480);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 8);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(53);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setVolume(3, 4);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(53);
  YMZ.setTonePeriod(3, 0);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 0);
  YMZ.setTone(3, false);
  YMZ.setTone(4, false);
  YMZ.setTone(5, false);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(64);
  YMZ.setVolume(3, 8);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(53);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setVolume(3, 4);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(53);
  YMZ.setTonePeriod(3, 339);
  YMZ.setTonePeriod(4, 381);
  YMZ.setTonePeriod(5, 453);
  YMZ.setTone(3, true);
  YMZ.setTone(4, true);
  YMZ.setTone(5, true);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setTonePeriod(3, 320);
  YMZ.setTonePeriod(4, 403);
  YMZ.setTonePeriod(5, 427);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 8);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(53);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setVolume(3, 4);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(53);
  YMZ.setTonePeriod(3, 339);
  YMZ.setTonePeriod(4, 381);
  YMZ.setTonePeriod(5, 453);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setTonePeriod(3, 320);
  YMZ.setTonePeriod(4, 403);
  YMZ.setTonePeriod(5, 427);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 8);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(53);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setVolume(3, 4);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(53);
  YMZ.setTonePeriod(3, 0);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 0);
  YMZ.setTone(3, false);
  YMZ.setTone(4, false);
  YMZ.setTone(5, false);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(64);
  YMZ.setVolume(3, 8);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(53);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setVolume(3, 4);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(53);
  YMZ.setTonePeriod(3, 571);
  YMZ.setTonePeriod(4, 603);
  YMZ.setTone(3, true);
  YMZ.setTone(4, true);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setTonePeriod(3, 285);
  YMZ.setTonePeriod(4, 301);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  delay(64);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  delay(64);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setTonePeriod(3, 480);
  YMZ.setTonePeriod(4, 507);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  delay(64);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  delay(53);
  YMZ.setTonePeriod(3, 240);
  YMZ.setTonePeriod(4, 253);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(64);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  delay(53);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  delay(53);
  YMZ.setTonePeriod(3, 427);
  YMZ.setTonePeriod(4, 453);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  delay(64);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setTonePeriod(3, 213);
  YMZ.setTonePeriod(4, 253);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  delay(64);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  delay(64);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  delay(53);
  YMZ.setTonePeriod(3, 360);
  YMZ.setTonePeriod(4, 381);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  delay(53);
  YMZ.setTonePeriod(3, 179);
  YMZ.setTonePeriod(4, 189);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  delay(53);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  delay(64);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setTonePeriod(3, 360);
  YMZ.setTonePeriod(4, 403);
  YMZ.setTonePeriod(5, 717);
  YMZ.setTone(5, true);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setTonePeriod(3, 320);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setTonePeriod(3, 285);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  delay(63);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(53);
  YMZ.setTonePeriod(3, 269);
  YMZ.setTonePeriod(4, 427);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 9);
  YMZ.setVolume(5, 9);
  delay(53);
  YMZ.setVolume(3, 8);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 7);
  YMZ.setVolume(5, 7);
  delay(53);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 5);
  YMZ.setVolume(5, 5);
  delay(53);
  YMZ.setVolume(3, 4);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 3);
  YMZ.setVolume(4, 3);
  YMZ.setVolume(5, 3);
  delay(53);
  YMZ.setTonePeriod(3, 0);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 0);
  YMZ.setTone(3, false);
  YMZ.setTone(4, false);
  YMZ.setTone(5, false);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 9);
  YMZ.setVolume(5, 9);
  delay(117);
  YMZ.setVolume(3, 8);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(53);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 7);
  YMZ.setVolume(5, 7);
  delay(53);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(86);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(86);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 5);
  YMZ.setVolume(5, 5);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(86);
  YMZ.setTonePeriod(0, 0);
  YMZ.mute();
  YMZ.setVolume(0, 14);
  delay(14);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 4);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(53);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 3);
  YMZ.setVolume(4, 3);
  YMZ.setVolume(5, 3);
  delay(53);
  YMZ.setTonePeriod(0, 0);
  YMZ.mute();
  YMZ.setVolume(0, 14);
  delay(14);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(86);
  YMZ.setVolume(3, 2);
  YMZ.setVolume(4, 2);
  YMZ.setVolume(5, 2);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(86);
  YMZ.setVolume(3, 1);
  YMZ.setVolume(4, 1);
  YMZ.setVolume(5, 1);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(87);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(13);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(3);
  YMZ.setVolume(0, 2);
  delay(14);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 0);
  YMZ.setVolume(4, 0);
  YMZ.setVolume(5, 0);
  delay(53);
  YMZ.setTone(3, true);
  YMZ.setTone(4, true);
  YMZ.setTone(5, true);
  YMZ.setNoise(3, true);
  YMZ.setNoise(4, true);
  YMZ.setNoise(5, true);
  YMZ.setNoisePeriod(0);
  YMZ.setTonePeriod(0, 0);
  YMZ.setNoisePeriod(0);
  delay(16);
  YMZ.setTonePeriod(3, 453);
  YMZ.setTonePeriod(4, 539);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setNoise(3, false);
  YMZ.setNoise(4, false);
  YMZ.setNoise(5, false);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(10);
  YMZ.setNoisePeriod(8);
  YMZ.setVolume(0, 2);
  delay(2);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTonePeriod(1, 0);
  YMZ.setTonePeriod(2, 0);
  YMZ.setNoisePeriod(8);
  YMZ.setVolume(0, 0);
  YMZ.setVolume(1, 7);
  YMZ.setVolume(2, 7);
  delay(13);
  YMZ.setTonePeriod(3, 0);
  YMZ.setTonePeriod(4, 0);
  delay(20);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 427);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(64);
  YMZ.setTonePeriod(3, 453);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 427);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 453);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 427);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 0);
  YMZ.setTone(5, false);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 453);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setTone(5, true);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 427);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(4, 717);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 480);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 539);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 640);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 539);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(12);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 8);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(4, 360);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setTone(4, false);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(4, 381);
  YMZ.setTone(4, true);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(4, 360);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 4);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(64);
  YMZ.setTonePeriod(3, 0);
  YMZ.setTonePeriod(4, 381);
  YMZ.setTonePeriod(5, 0);
  YMZ.setTone(3, false);
  YMZ.setTone(5, false);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(4, 360);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setTone(5, true);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 717);
  YMZ.setTonePeriod(4, 853);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setTone(3, true);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 0);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 539);
  YMZ.setTonePeriod(4, 717);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 453);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(12);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 427);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(64);
  YMZ.setTonePeriod(3, 453);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 427);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 453);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 427);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 0);
  YMZ.setTone(5, false);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 453);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setTone(5, true);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 427);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(4, 717);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 480);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 539);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 640);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 480);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 960);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(12);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(4, 603);
  YMZ.setTonePeriod(5, 1123);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 8);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(4, 571);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setTone(4, false);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(4, 603);
  YMZ.setTone(4, true);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(4, 571);
  YMZ.setTonePeriod(5, 1123);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setVolume(3, 4);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(64);
  YMZ.setTonePeriod(3, 0);
  YMZ.setTonePeriod(4, 603);
  YMZ.setTonePeriod(5, 0);
  YMZ.setTone(3, false);
  YMZ.setTone(5, false);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(4, 571);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setTone(5, true);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 717);
  YMZ.setTonePeriod(4, 805);
  YMZ.setTonePeriod(5, 1709);
  YMZ.setTone(3, true);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 0);
  YMZ.setTonePeriod(5, 1917);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 539);
  YMZ.setTonePeriod(5, 1709);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 453);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(12);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 427);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(64);
  YMZ.setTonePeriod(3, 453);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 427);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 453);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 427);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 0);
  YMZ.setTone(5, false);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 453);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setTone(5, true);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 427);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 453);
  YMZ.setTonePeriod(4, 640);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 539);
  YMZ.setTonePeriod(4, 717);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 427);
  YMZ.setTonePeriod(4, 0);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 339);
  YMZ.setTonePeriod(4, 403);
  YMZ.setTonePeriod(5, 805);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(12);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 320);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 960);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(64);
  YMZ.setTonePeriod(3, 339);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 320);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 339);
  YMZ.setTonePeriod(5, 960);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 320);
  YMZ.setTonePeriod(5, 805);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 0);
  YMZ.setTone(5, false);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(3, 339);
  YMZ.setTonePeriod(5, 805);
  YMZ.setTone(5, true);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 320);
  YMZ.setTonePeriod(5, 960);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 360);
  YMZ.setTonePeriod(4, 427);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 403);
  YMZ.setTonePeriod(4, 480);
  YMZ.setTonePeriod(5, 960);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 480);
  YMZ.setTonePeriod(4, 640);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 453);
  YMZ.setTonePeriod(4, 539);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(12);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 427);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(64);
  YMZ.setTonePeriod(3, 360);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(64);
  YMZ.setTonePeriod(3, 427);
  YMZ.setTonePeriod(4, 717);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 453);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 539);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 507);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 0);
  YMZ.setTone(5, false);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 480);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setTone(5, true);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 1709);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(64);
  YMZ.setTonePeriod(3, 360);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setTonePeriod(5, 1917);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(64);
  YMZ.setTonePeriod(3, 480);
  YMZ.setTonePeriod(4, 805);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 539);
  YMZ.setTonePeriod(5, 1709);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 571);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 539);
  YMZ.setTonePeriod(4, 853);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(12);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTonePeriod(0, 0);
  YMZ.setTone(0, false);
  YMZ.setNoise(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(14);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 805);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  delay(65);
  YMZ.setTonePeriod(4, 853);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(64);
  YMZ.setTonePeriod(3, 0);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 0);
  YMZ.setTone(3, false);
  YMZ.setTone(4, false);
  YMZ.setTone(5, false);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.mute();
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 10);
  YMZ.setVolume(4, 9);
  YMZ.setVolume(5, 9);
  delay(64);
  YMZ.setVolume(3, 9);
  YMZ.setVolume(4, 8);
  YMZ.setVolume(5, 8);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 8);
  YMZ.setVolume(4, 7);
  YMZ.setVolume(5, 7);
  delay(64);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 6);
  YMZ.setVolume(4, 5);
  YMZ.setVolume(5, 5);
  delay(64);
  YMZ.setVolume(3, 5);
  YMZ.setVolume(4, 4);
  YMZ.setVolume(5, 4);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 4);
  YMZ.setVolume(4, 3);
  YMZ.setVolume(5, 3);
  delay(65);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 0);
  YMZ.mute();
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setNoise(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(3, 717);
  YMZ.setTonePeriod(4, 960);
  YMZ.setTonePeriod(5, 1437);
  YMZ.setTone(3, true);
  YMZ.setTone(4, true);
  YMZ.setTone(5, true);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTonePeriod(0, 1077);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(5, 1280);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(65);
  YMZ.setTonePeriod(5, 1123);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(13);
  YMZ.setVolume(0, 2);
  delay(3);
  YMZ.setVolume(0, 0);
  delay(33);
  YMZ.setVolume(3, 7);
  YMZ.setVolume(4, 6);
  YMZ.setVolume(5, 6);
  delay(66);
  YMZ.setTonePeriod(3, 0);
  YMZ.setTonePeriod(4, 0);
  YMZ.setTonePeriod(5, 1077);
  YMZ.setVolume(3, 11);
  YMZ.setVolume(4, 10);
  YMZ.setVolume(5, 10);
  YMZ.setTone(0, false);
  YMZ.setVolume(0, 14);
  delay(3);
  YMZ.setTone(0, true);
  YMZ.setVolume(0, 8);
  delay(12);
  YMZ.setVolume(0, 2);
  delay(2);
}

