
#include <hcYmzShield.h>

void setup() {
  Serial.begin(9600);
  Serial.println("MIDI2PSG Output");
}


void loop() {
  YMZ.setVolume(0xa);
  // 
  YMZ.setTempo(138);
  YMZ.beat( 1, DOUBLEDOT);
  YMZ.setChannels(  71,  OFF,   57,  OFF,   67,  OFF); YMZ.beat( 8);
  YMZ.setChannels(  72, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,  OFF, SKIP,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   79, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  84, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  95, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  93, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  91, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP,   86, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  91, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  91, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  93, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  95, SKIP, SKIP, SKIP,   60, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   67, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  93, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  91, SKIP,   57, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP,   59, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat(16);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,  OFF, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF,   64,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   59, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,  OFF,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  78, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  75, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  73, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  76, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  85, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  76, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels(  68, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  78, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  75, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  73, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  76, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  75, SKIP,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  85, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  76, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels( OFF, SKIP,   45, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73,  OFF,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   42, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73,  OFF,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,  OFF, SKIP, SKIP,   37); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   44, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61,   51, SKIP, SKIP,  OFF); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   44, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78,  OFF,  OFF, SKIP, SKIP,   37); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   44, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP, SKIP, SKIP,   61,  OFF); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   45, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   42, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,  OFF, SKIP, SKIP,   35); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   42, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF,  OFF,   59, SKIP, SKIP,  OFF); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP,   75, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  95, SKIP, SKIP, SKIP,   71, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels(  71,   64,   45, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83,  OFF, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   71, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   44, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   63, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71,   64,   45, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83,  OFF, SKIP, SKIP,   68, SKIP); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  80, SKIP,   49, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   47, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   63, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71,   64,   45, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83,  OFF, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   71, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   44, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   49, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF,   63,   47, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71,   64,   42, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83,  OFF, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   57, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   42, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   35); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels(  71, SKIP,   57, SKIP,   67,  OFF); YMZ.beat( 8);
  YMZ.setChannels(  72, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,  OFF, SKIP,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   79, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  84, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  95, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  93, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  91, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP,   86, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  91, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  91, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  93, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  95, SKIP, SKIP, SKIP,   60, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   67, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  93, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  91, SKIP,   57, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   72, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP,   59, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat(16);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,  OFF, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF,   64,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   59, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,  OFF,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  78, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  75, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  73, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  76, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  85, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  76, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels(  68, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  78, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  75, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  73, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  76, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  75, SKIP,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  85, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  76, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels( OFF, SKIP,   45, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73,  OFF,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   42, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73,  OFF,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,  OFF, SKIP, SKIP,   37); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   44, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61,   51, SKIP, SKIP,  OFF); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   44, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78,  OFF,  OFF, SKIP, SKIP,   37); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   44, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP, SKIP, SKIP,   61,  OFF); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   45, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   42, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,  OFF, SKIP, SKIP,   35); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   42, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF,  OFF,   59, SKIP, SKIP,  OFF); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP,   75, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  95, SKIP, SKIP, SKIP,   71, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels(  80, SKIP,  OFF, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   63, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP,   59, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP,  OFF, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   63, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  97, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  95, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP,   59, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP,  OFF, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   63, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP,   59, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP,  OFF, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   63, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  97, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  95, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP,   59, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP,  OFF, SKIP,   61, SKIP); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels( OFF, SKIP,   57, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP,  OFF, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP,   54, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP,  OFF, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   63, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP,   49, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   63, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP,   71, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP,   49, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   63, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  87, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   68, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP,   45, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73,  OFF,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   42, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73,  OFF,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,  OFF, SKIP, SKIP,   35); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   42, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68,   61,   51, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF,  OFF,   59, SKIP, SKIP,  OFF); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP,   75, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  95, SKIP, SKIP, SKIP,   71, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels(  71,   64,   45, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83,  OFF, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   71, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   44, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   63, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71,   64,   45, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83,  OFF, SKIP, SKIP,   68, SKIP); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  80, SKIP,   49, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  75, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   47, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   63, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71,   64,   45, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83,  OFF, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   71, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 4);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   44, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71,  OFF,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF,   63,   47, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64,   56, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71,   64,   42, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83,  OFF, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP,   57, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   42, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   35); YMZ.beat( 4, DOT);
  YMZ.setChannels( OFF, SKIP,   45, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP,  OFF); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   55, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP,   59, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   60, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  69, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  67, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,  OFF,   55, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels( OFF, SKIP,   59, SKIP,   62, SKIP); YMZ.beat(32);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  67, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  67, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  69, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,  OFF,   57, SKIP,   60, SKIP); YMZ.beat(32);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP,   67, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  72, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   71, SKIP); YMZ.beat(32);
  YMZ.setChannels( OFF, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(32);
  YMZ.setChannels(  78, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   55, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   62, SKIP); YMZ.beat(32);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  69, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   45, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP,  OFF, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  72, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  69, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF, SKIP,  OFF, SKIP, SKIP,   35); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   45, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  69,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF,   47, SKIP,  OFF,  OFF); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  69, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF,  OFF, SKIP,  OFF,   35); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   42, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   45, SKIP, SKIP,  OFF); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   49, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   52, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels( OFF, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  69, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels( OFF,   59,  OFF, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  66,  OFF, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  69, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  93, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  92, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP,   59, SKIP,   69, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP,  OFF, SKIP,   64, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   71, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   59, SKIP,   66, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP,   52, SKIP,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  73, SKIP,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP,   61, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   61,   54, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   59, SKIP, SKIP, SKIP,   35); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   54, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   56, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF,   64,   40, SKIP,  OFF,  OFF); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   56, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   52, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   54, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   56, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   61,   45, SKIP, SKIP,   35); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   59, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  66, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81,  OFF,  OFF, SKIP, SKIP,   26); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels( OFF,   64,   53, SKIP, SKIP,  OFF); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   62,   52, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  71,   64,   47, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  69,  OFF,   38, SKIP, SKIP, SKIP); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels( OFF, SKIP,   50, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   64, SKIP); YMZ.beat(16);
  YMZ.setChannels(  69, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  88, SKIP,  OFF, SKIP,  OFF,   28); YMZ.beat( 1, DOUBLEDOT);
  YMZ.setChannels( OFF,  OFF,  OFF,  OFF,  OFF,  OFF); YMZ.mute();
   delay(3000); // Repeat every 3 seconds
}
