/**
 * Final Fantasy VII Demo
 * Derrick Sobodash <derrick@sobodash.com>
 * Version 0.3.0
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer. 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution. 
 */

#include <hcYmzShield.h>


void setup() {
  Serial.begin(9600);
  Serial.println("Those Who Fight - Final Fantasy VII by Nobuo Uematsu");
}


void loop() {
  PSG.setVolume(0xd);
  
  PSG.setArticulation(LEGATO);
  PSG.setTempo(185);
  
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,  OFF, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  72,   60, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   63, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  78,   66, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   63, SKIP, SKIP,   42, SKIP); PSG.beat( 8);
  PSG.setChannels(  78,   66, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,  OFF, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  68,   67, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   72, SKIP, SKIP,   42,   75); PSG.beat( 4);
  PSG.setChannels(  75,   71, SKIP, SKIP,   42,   75); PSG.beat( 4);
  PSG.setChannels(  75,   70, SKIP, SKIP,   42,   75); PSG.beat( 4);
  PSG.setChannels(  77,   65,   65, SKIP,   41,   77); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,  OFF, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   60,   53,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  72,   60,   60,   53,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   63,   60,   53,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  78,   66,   63,  OFF,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   63,   60,   56,   42, SKIP); PSG.beat( 8);
  PSG.setChannels(  78,   66, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   58,   55,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP,   56,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP,   55,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP,   53,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41,   72); PSG.beat( 8);
  PSG.setChannels(  72,   70, SKIP, SKIP,   42,   75); PSG.beat( 4);
  PSG.setChannels(  75,   68, SKIP, SKIP,   42,   75); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   75); PSG.beat( 8);
  PSG.setChannels(  78,   66, SKIP, SKIP,   42,  OFF); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   75); PSG.beat( 8);
  PSG.setChannels(  53,   48, SKIP,   53,   41,  OFF); PSG.beat( 8);
  PSG.setChannels(  53,   48, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  53,   48, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  55,   51, SKIP,   55,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  55,   51, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  55,   51, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  56,   53, SKIP,   56,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  56,   53, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  56,   53, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  58,   55,   58,   51,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  58,   55, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  58,   55, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  60,   56,   60,   56,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  60,   56, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  63,   58,   63,   55,   39, SKIP); PSG.beat( 8);
  PSG.setChannels(  63,   58, SKIP, SKIP,   39, SKIP); PSG.beat( 8);
  PSG.setChannels(  65,   61,   65,   53,   37,   65); PSG.beat( 8);
  PSG.setChannels(  65,   61, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  65,   61, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  67,   63, SKIP, SKIP,   37,   67); PSG.beat( 8);
  PSG.setChannels(  67,   63, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  67,   63, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  68,   65, SKIP, SKIP,   37,   68); PSG.beat( 8);
  PSG.setChannels(  68,   65, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  68,   65, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  70,   67, SKIP, SKIP,   37,   70); PSG.beat( 8);
  PSG.setChannels(  70,   67, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  70,   67, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  72,   68, SKIP, SKIP,   37,   72); PSG.beat( 8);
  PSG.setChannels(  72,   68, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   70, SKIP, SKIP,   36,   75); PSG.beat( 8);
  PSG.setChannels(  75,   70, SKIP, SKIP,   36, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   73,   70, SKIP,   34,   77); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  79,   75,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  80,   77,   68, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  82,   79,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  84,   80,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  65, SKIP,   68, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  65, SKIP,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels( OFF,   77,  OFF, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  65,  OFF, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  65, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(  65, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  67, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(  67, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  70, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(  70, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  67, SKIP, SKIP, SKIP,   42, SKIP); PSG.beat(16);
  PSG.setChannels(  67, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  70, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  70, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  65,   77,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels( OFF,   79,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  65,   80,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   80, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   82,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   82, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   80,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   80, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   79,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   82,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   82, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   80,   65, SKIP,   41,   77); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  63,   75, SKIP, SKIP,   42, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   78,   60,   54, SKIP,   78); PSG.beat( 8);
  PSG.setChannels(  63, SKIP, SKIP,  OFF,   42,  OFF); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   60,   54, SKIP,   78); PSG.beat( 8);
  PSG.setChannels(  66, SKIP,   59,   54,   42,   75); PSG.beat( 4);
  PSG.setChannels(  53,   48, SKIP,   53,   41,  OFF); PSG.beat( 8);
  PSG.setChannels(  53,   48, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  53,   48, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  55,   51, SKIP,   55,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  55,   51, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  55,   51, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  56,   53, SKIP,   56,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  56,   53, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  56,   53, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  58,   55,   58,   51,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  58,   55, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  58,   55, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  60,   56,   60,   56,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  60,   56, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  63,   58,   63,   55,   39, SKIP); PSG.beat( 8);
  PSG.setChannels(  63,   58, SKIP, SKIP,   39, SKIP); PSG.beat( 8);
  PSG.setChannels(  65,   61,   65,   53,   37,   65); PSG.beat( 8);
  PSG.setChannels(  65,   61, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  65,   61, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  67,   63, SKIP, SKIP,   37,   67); PSG.beat( 8);
  PSG.setChannels(  67,   63, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  67,   63, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  68,   65, SKIP, SKIP,   37,   68); PSG.beat( 8);
  PSG.setChannels(  68,   65, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  68,   65, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  70,   67, SKIP, SKIP,   37,   70); PSG.beat( 8);
  PSG.setChannels(  70,   67, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  70,   67, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  72,   68, SKIP, SKIP,   37,   72); PSG.beat( 8);
  PSG.setChannels(  72,   68, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   70, SKIP, SKIP,   36,   75); PSG.beat( 8);
  PSG.setChannels(  75,   70, SKIP, SKIP,   36, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   73,   70, SKIP,   34,   77); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  79,   75,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  80,   77,   68, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  82,   79,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  84,   80,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   67, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  65, SKIP,   68, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  65, SKIP,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels( OFF,   77,  OFF, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  65,  OFF, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  65, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(  65, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  67, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(  67, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  70, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(  70, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  67, SKIP, SKIP, SKIP,   42, SKIP); PSG.beat(16);
  PSG.setChannels(  67, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  70, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  70, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  65,   77,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels( OFF,   79,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  65,   80,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   80, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   82,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   82, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   80,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   80, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   79,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   82,   65, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   82, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   80,   65, SKIP,   41,   77); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  63,   75, SKIP, SKIP,   42, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   78,   60,   54, SKIP,   78); PSG.beat( 8);
  PSG.setChannels(  63, SKIP, SKIP,  OFF,   42,  OFF); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   60,   54, SKIP,   78); PSG.beat( 8);
  PSG.setChannels(  66, SKIP,   59,   54,   42,   75); PSG.beat( 4);
  PSG.setChannels(  65, SKIP, SKIP,  OFF,   41,  OFF); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  65, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels( OFF,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  65,  OFF, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  65, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(  65, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  67, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(  67, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  70, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(  70, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  67, SKIP, SKIP, SKIP,   42, SKIP); PSG.beat(16);
  PSG.setChannels(  67, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  70, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  70, SKIP, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  68, SKIP, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  65,   77, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels( OFF,   79, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  65,   80, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   80, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   82, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   82, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   80, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   80, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   79, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   72, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   72, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   77, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   76, SKIP, SKIP,   41, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   76, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  65,   77, SKIP, SKIP,   41,   77); PSG.beat(16);
  PSG.setChannels(SKIP,   77, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  64,   80, SKIP, SKIP,   40,   76); PSG.beat(16);
  PSG.setChannels(SKIP,   80, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   79, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  63,   80, SKIP, SKIP,   39,   75); PSG.beat(16);
  PSG.setChannels(SKIP,   80, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   82, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,   82, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(SKIP,  OFF, SKIP, SKIP,   37,   73); PSG.beat( 8);
  PSG.setChannels(  84,   72, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  83,   71, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  84,   72, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  82,   70, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  80,   68, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  79,   67, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  80,   68, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  73,   61,   61,   53,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  72,   60, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   63,   56,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  73,   61, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   68, SKIP,   37,   68); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37,   67); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37,   68); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37,   70); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37,   72); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37,   73); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37,   75); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37,   73); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37,   75); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   37,   77); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   36,   79); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   36,   80); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34,   82); PSG.beat( 8);
  PSG.setChannels(  80,   68, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  76,   64, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  79,   67, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   63, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  73,   61, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  70,   58, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  72,   60, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  73,   61, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   63, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  73,   61, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  73,   61, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  70,   58,   61, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   60,   53,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP,   58,   49,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP,   34, SKIP); PSG.beat( 8);
  PSG.setChannels(  70,   58, SKIP,   56,   34, SKIP); PSG.beat(16);
  PSG.setChannels(  70,   58, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  72,   60, SKIP, SKIP,   34, SKIP); PSG.beat(16);
  PSG.setChannels(  72,   60, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  73,   61, SKIP, SKIP,   34, SKIP); PSG.beat(16);
  PSG.setChannels(  73,   61, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  75,   63, SKIP,   55,   34, SKIP); PSG.beat(16);
  PSG.setChannels(  75,   63, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  77,   65, SKIP, SKIP,   34, SKIP); PSG.beat(16);
  PSG.setChannels(  77,   65, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  79,   67, SKIP,   51,   34, SKIP); PSG.beat(16);
  PSG.setChannels(  79,   67, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  80,   68, SKIP, SKIP,   34, SKIP); PSG.beat(16);
  PSG.setChannels(  80,   68, SKIP, SKIP, SKIP, SKIP); PSG.beat(16);
  PSG.setChannels(  77,   72, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   89); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   92); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   91); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   94); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,  OFF); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   92); PSG.beat( 8);
  PSG.setChannels(  77,   72,   72, SKIP, SKIP,   96); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   94); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   97); PSG.beat( 8);
  PSG.setChannels(  77,   72,   70, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   96); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP,   41,   92); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   89); PSG.beat( 8);
  PSG.setChannels(  77,   73,   68, SKIP,   37,  OFF); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   89); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   92); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   91); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   94); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,  OFF); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   92); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   96); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   94); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   97); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   96); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP,   37,   92); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   89); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP,   39,  OFF); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   87); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   91); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   89); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   92); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,  OFF); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   91); PSG.beat( 8);
  PSG.setChannels(  79,   75,   70, SKIP, SKIP,   94); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   92); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   96); PSG.beat( 8);
  PSG.setChannels(  79,   75,   67, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   94); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP,   39,   91); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   87); PSG.beat( 8);
  PSG.setChannels(  77,   72,   68, SKIP,   41,  OFF); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   89); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   92); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   91); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   94); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,  OFF); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   92); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   96); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   94); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   97); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   96); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP,   41,   92); PSG.beat( 8);
  PSG.setChannels(  77,   72, SKIP, SKIP, SKIP,   89); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP,   37,  OFF); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   89); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   92); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   91); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   94); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,  OFF); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   92); PSG.beat( 8);
  PSG.setChannels(  77,   73,   72, SKIP, SKIP,   96); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   94); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   97); PSG.beat( 8);
  PSG.setChannels(  77,   73,   68, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   96); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP,   37,   92); PSG.beat( 8);
  PSG.setChannels(  77,   73, SKIP, SKIP, SKIP,   89); PSG.beat( 8);
  PSG.setChannels(  79,   75,   67, SKIP,   39,  OFF); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   87); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   91); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   89); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   92); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,  OFF); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   91); PSG.beat( 8);
  PSG.setChannels(  79,   75, SKIP, SKIP, SKIP,   94); PSG.beat( 8);
  PSG.setChannels(  79,   75,   67, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  79,   75,   67, SKIP, SKIP,   92); PSG.beat( 8);
  PSG.setChannels(  79,   75,   67, SKIP, SKIP,   96); PSG.beat( 8);
  PSG.setChannels(  79,   75,   67, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  79,   75,   67, SKIP, SKIP,   94); PSG.beat( 8);
  PSG.setChannels(  79,   75,   67, SKIP,   39,   91); PSG.beat( 8);
  PSG.setChannels(  79,   75,   67, SKIP, SKIP,   87); PSG.beat( 8);
  PSG.setChannels(  77,   65,   68, SKIP,   41,  OFF); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  72,   60, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   63, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  78,   66, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   63, SKIP, SKIP,   42, SKIP); PSG.beat( 8);
  PSG.setChannels(  78,   66, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,  OFF, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  68,   67, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   72, SKIP, SKIP,   42,   75); PSG.beat( 4);
  PSG.setChannels(  75,   71, SKIP, SKIP,   42,   75); PSG.beat( 4);
  PSG.setChannels(  75,   70, SKIP, SKIP,   42,   75); PSG.beat( 4);
  PSG.setChannels(  77,   65,   65, SKIP,   41,   77); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,  OFF, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   65, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65,   60,   53,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  72,   60,   60,   53,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   63,   60,   53,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  78,   66,   63,  OFF,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  75,   63,   60,   56,   42, SKIP); PSG.beat( 8);
  PSG.setChannels(  78,   66, SKIP, SKIP, SKIP, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP,   55,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP,   56,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP,   55,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP,   53,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41, SKIP); PSG.beat( 8);
  PSG.setChannels(  77,   65, SKIP, SKIP,   41,   72); PSG.beat( 8);
  PSG.setChannels(  72,   70, SKIP, SKIP,   42,   75); PSG.beat( 4);
  PSG.setChannels(  75,   68, SKIP, SKIP,   42,   75); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   75); PSG.beat( 8);
  PSG.setChannels(  78,   66, SKIP, SKIP,   42,  OFF); PSG.beat( 8);
  PSG.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   75); PSG.beat( 8);
  
  PSG.mute();
}


