
#include <hcYmzShield.h>

void setup() {
  Serial.begin(9600);
  Serial.println("MIDI2PSG Output");
}


void loop() {
  YMZ.setVolume(0xa);
  // 
  YMZ.setTempo(100);
   YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  93, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   93, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  91, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   91, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   90, SKIP); YMZ.beat(16);
  YMZ.setChannels(  86, SKIP, SKIP, SKIP,   86, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   85, SKIP); YMZ.beat(16);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(16);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP,   79, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat(16);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   69,   69, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16);
  YMZ.setChannels(  74,   69, SKIP,   67, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP,   74, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  76, SKIP, SKIP,   61, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  78, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  76,   69, SKIP,   66, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP,   76, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  73, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(SKIP,   71, SKIP,   64, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  73, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  73,   66, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP,   73, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels( OFF,   57,  OFF, SKIP,  OFF, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   62, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP,   43); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,   62, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   61, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP,   62, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62,  OFF, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP,   69, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   68,  OFF,   59, SKIP,  OFF); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   68, SKIP, SKIP,   53); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   67,  OFF,  OFF, SKIP,  OFF); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   67, SKIP, SKIP,   40); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP,   47); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   67, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   62, SKIP,   59, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(SKIP,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,  OFF, SKIP,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   65, SKIP,   55, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   65, SKIP, SKIP,   45); YMZ.beat( 8, DOT);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(SKIP,   71,   71, SKIP, SKIP, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP,   38); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat( 4, DOT);
  YMZ.setChannels(  81,  OFF, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  93, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   93, SKIP); YMZ.beat( 4);
  YMZ.setChannels( OFF, SKIP, SKIP, SKIP,  OFF,   38); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat( 4, TRIPLEDOT);
  YMZ.setChannels(SKIP,   57, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   57,  OFF, SKIP,  OFF); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   62, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP,   38); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   45); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66,  OFF, SKIP,  OFF); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   47); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP,   61, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   62,  OFF,   59, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(SKIP,   64,  OFF,  OFF, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP,   40); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP,   47); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   62, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 4, DOUBLEDOT);
  YMZ.setChannels(SKIP,   59, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   59, SKIP, SKIP,   43); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   62, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   61, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   59,  OFF,  OFF, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   59, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   57, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   57, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   62, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP,   38); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   45); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP,  OFF,   73,  OFF); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF,  OFF, SKIP, SKIP,   42); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP,   61, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat( 4, DOT);
  YMZ.setChannels(SKIP,   69,  OFF, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  73, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   71, SKIP,  OFF, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP, SKIP,   43); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels( OFF, SKIP, SKIP,   55,  OFF, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   69, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   71, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,  OFF, SKIP,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   61, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   69,  OFF, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  74, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74,   47); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,  OFF, SKIP,   64, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74, SKIP, SKIP,   66, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   71, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   71, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,  OFF, SKIP,   42); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP,   61, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(SKIP,   62, SKIP,   59, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   66, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   71, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP, SKIP,   43); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   71, SKIP,   67, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   69, SKIP,   66, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   67, SKIP,   64, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   67, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   67, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP,   48); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   64, SKIP,   58, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   66, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   67, SKIP, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   74, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP,   81, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP,  OFF); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   62, SKIP,   61, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF,  OFF, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   59, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   59, SKIP, SKIP,   45); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   62, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat( 4, DOT);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   85, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  83,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP,   83, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP,  OFF); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP,   50); YMZ.beat( 8, DOT);
  YMZ.setChannels(  93, SKIP, SKIP, SKIP,   93, SKIP); YMZ.beat(16);
  YMZ.setChannels(  91, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   91, SKIP); YMZ.beat(16);
  YMZ.setChannels(  90, SKIP, SKIP, SKIP,   90, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  86, SKIP, SKIP, SKIP,   86, SKIP); YMZ.beat(16);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(32);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   79, SKIP); YMZ.beat(32);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP,  OFF,  OFF, SKIP,   78, SKIP); YMZ.beat(32);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  74, SKIP,  OFF, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP,   61, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81,   49); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  78, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   47); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  76,   69, SKIP,   61, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP,   76, SKIP); YMZ.beat(32);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(32);
  YMZ.setChannels(  73, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   66, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   61, SKIP, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  76,   71, SKIP,  OFF, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   76,   40); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78,   47); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74,   52); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   66, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   71, SKIP,   64, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,  OFF,  OFF, SKIP, SKIP,   45); YMZ.beat(16);
  YMZ.setChannels(SKIP,   67,   62, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  76,   71,   71, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   62, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   59, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels( OFF, SKIP,   59, SKIP,  OFF, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   61, SKIP,   55, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   61, SKIP, SKIP,   45); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP,  OFF, SKIP,  OFF); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP,   61, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP,   66, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  85, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   85,  OFF); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   42); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  76,   69, SKIP,   61, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP,   76, SKIP); YMZ.beat(32);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(32);
  YMZ.setChannels(  73, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,  OFF,  OFF); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   85,   43); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  86, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   86,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  83, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   83, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  83, SKIP, SKIP,   67, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   83, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,  OFF, SKIP,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   71, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels( OFF, SKIP, SKIP, SKIP,  OFF,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  73,   71,  OFF,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   73, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  86, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   86,   47); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   61, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  86, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   86,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  85, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   85, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  83,   71, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   83, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  83,   71, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   83,   54); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   42); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP,   81,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   61, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78,   66, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP,   78, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  83,   71, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   83,   43); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   83, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP,  OFF,  OFF, SKIP,   79, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74,   71, SKIP,   56, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,  OFF, SKIP,   45); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   61, SKIP, SKIP, SKIP,  OFF); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   61, SKIP, SKIP,   43); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   64, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74,   42); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  76, SKIP, SKIP,   57,  OFF, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   79, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,  OFF, SKIP,   40); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   47); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   79, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  74,   71, SKIP,   66, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  73,   69, SKIP,   64, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP,   73,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   71, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP, SKIP,   52); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  76,   71,  OFF, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   76,   45); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP,   74,   38); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   61, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   67, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   67, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   66, SKIP,   61, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   64, SKIP,   59, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   64, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(SKIP,   66,  OFF,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP,   50); YMZ.beat( 4, TRIPLEDOT);
  YMZ.setChannels(  74,  OFF,  OFF,  OFF, SKIP,  OFF); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(  85, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   85, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP,   69, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   83, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  83, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   83, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   67, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   66, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   83, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   85, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  86, SKIP, SKIP, SKIP,   86, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   83,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP,   67, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   66, SKIP, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   61, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP,  OFF); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(16);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP,   79, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81,   48); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   79, SKIP); YMZ.beat(32);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat(32);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   79,   48); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP,  OFF); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   79,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat(32);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP,   83, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP,   61, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83,   71, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   83,   38); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP,   81,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81,   71, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   81,   40); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   41); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   56, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   53); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74,   62, SKIP,   60, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP,   74,   52); YMZ.beat( 8, DOT);
  YMZ.setChannels(  78,   66,   66, SKIP,   78, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,  OFF, SKIP,   50); YMZ.beat(16);
  YMZ.setChannels(  81,   69,   69, SKIP,   81, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   85,   43); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,  OFF,  OFF,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83,   71, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   83, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  83,   71, SKIP,   59, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   83, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   67, SKIP, SKIP); YMZ.beat( 4);
  YMZ.setChannels(SKIP, SKIP, SKIP,  OFF, SKIP,   44); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83,   71, SKIP,   64, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   83,   53); YMZ.beat( 8, DOT);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   85, SKIP); YMZ.beat(16);
  YMZ.setChannels(SKIP,  OFF,  OFF,   62, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  86, SKIP, SKIP, SKIP,   86, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   85,   42); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  81,   69, SKIP,   59, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP,   81, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   61, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  85, SKIP, SKIP,   69, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   85, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  83,   71, SKIP,   67, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   83, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   66, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   63, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels( OFF,  OFF,  OFF, SKIP,  OFF,   54); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   51); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81,   47); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81,   40); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  79, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   79, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  86, SKIP, SKIP,   66, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   86, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  79, SKIP, SKIP,   74, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   67, SKIP,   79,   52); YMZ.beat( 4, DOT);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(32);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat(32);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   54); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   61, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   43); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   66, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat( 4, TRIPLEDOT);
  YMZ.setChannels(SKIP,   69, SKIP,   61, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP,   54); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(SKIP,   67, SKIP,   59, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   67, SKIP, SKIP,   52); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(SKIP,   66, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP, SKIP,   50); YMZ.beat( 2);
  YMZ.setChannels(SKIP, SKIP, SKIP,  OFF, SKIP,   38); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   52); YMZ.beat( 8);
  YMZ.setChannels( OFF,  OFF,  OFF, SKIP,  OFF,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   64, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   69, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  78, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(16);
  YMZ.setChannels(  74, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  85, SKIP, SKIP,   71,   78, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   85, SKIP); YMZ.beat( 4, DOT);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   83, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   83, SKIP); YMZ.beat( 4, TRIPLEDOT);
  YMZ.setChannels(SKIP,   71, SKIP,   59, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  80, SKIP,   71,   68,   76, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   80, SKIP); YMZ.beat( 4, TRIPLEDOT);
  YMZ.setChannels(  83, SKIP,  OFF, SKIP,  OFF, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   83, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   85, SKIP); YMZ.beat( 8, DOT);
  YMZ.setChannels(  86, SKIP, SKIP, SKIP,   86, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(  85, SKIP, SKIP,   66,   78, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   85, SKIP); YMZ.beat( 4, DOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat( 4, DOT);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   85, SKIP); YMZ.beat( 8, DOUBLEDOT);
  YMZ.setChannels(  73, SKIP, SKIP,   64,  OFF, SKIP); YMZ.beat(32);
  YMZ.setChannels(  83, SKIP, SKIP,   69,   78, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   83, SKIP); YMZ.beat( 4, TRIPLEDOT);
  YMZ.setChannels(SKIP,   71, SKIP,   63, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP, SKIP, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP,  OFF, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  81,   71, SKIP,   67,  OFF, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   81, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  79,   71, SKIP,   67, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   71, SKIP,   79, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  86, SKIP, SKIP,   71, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   86, SKIP); YMZ.beat( 8, TRIPLEDOT);
  YMZ.setChannels(  79, SKIP, SKIP,   74,  OFF, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   79, SKIP); YMZ.beat( 4, DOT);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(32);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat(32);
  YMZ.setChannels(  78,   67, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   67, SKIP,   78,   46); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  78, SKIP, SKIP,   58, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   78, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  76, SKIP, SKIP,   69, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP,  OFF,  OFF, SKIP,   76, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74,   67, SKIP,   64, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   67, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   73,  OFF); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76,   43); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   55, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   59, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   62, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP,   65, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  74,   66, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   66, SKIP,   74,   38); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   45); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   50); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP, SKIP, SKIP,   57, SKIP, SKIP); YMZ.beat( 8);
  YMZ.setChannels(SKIP,   69, SKIP,   58, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP, SKIP,   48); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   62, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  72,   65, SKIP,   56, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   65, SKIP,   72,   46); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(SKIP,   62, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   62, SKIP, SKIP, SKIP); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  76,   69, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP,   69, SKIP,   76,   38); YMZ.beat( 8);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP, SKIP,   45); YMZ.beat(16, DOUBLEDOT);
  YMZ.setChannels(  88, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   88,   50); YMZ.beat(32);
  YMZ.setChannels(  86, SKIP, SKIP, SKIP,   86, SKIP); YMZ.beat(32);
  YMZ.setChannels(  85, SKIP, SKIP, SKIP,   85, SKIP); YMZ.beat(32);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(32);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   80, SKIP); YMZ.beat(32);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(32);
  YMZ.setChannels(  83, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   83, SKIP); YMZ.beat(32);
  YMZ.setChannels(  81, SKIP, SKIP, SKIP,   81, SKIP); YMZ.beat(32);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   80, SKIP); YMZ.beat(32);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat(32);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(32);
  YMZ.setChannels(  73, SKIP, SKIP, SKIP,   73, SKIP); YMZ.beat(32);
  YMZ.setChannels(  74, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP, SKIP, SKIP, SKIP,   74, SKIP); YMZ.beat(32);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP,   76, SKIP); YMZ.beat(32);
  YMZ.setChannels(  80, SKIP, SKIP, SKIP,   80, SKIP); YMZ.beat(32);
  YMZ.setChannels(  76, SKIP, SKIP, SKIP, SKIP, SKIP); YMZ.beat(32);
  YMZ.setChannels(SKIP,  OFF,  OFF, SKIP,   76,  OFF); YMZ.beat( 1);
  YMZ.setChannels( OFF,   71, SKIP, SKIP,  OFF, SKIP); YMZ.beat( 1);
  YMZ.setChannels( OFF,  OFF,  OFF,  OFF,  OFF,  OFF); YMZ.mute();
   delay(3000); // Repeat every 3 seconds
}
